resolver 127.0.0.11 valid=10s ipv6=off;

upstream client {
    server client:3000;
}

upstream server {
    server server:9090;
}

server {
    listen 80;
    server_name getlynx.tech www.getlynx.tech;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name getlynx.tech www.getlynx.tech;

    ssl_certificate /etc/letsencrypt/live/getlynx.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/getlynx.tech/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://client;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
}

server {
    listen 80;
    server_name api.getlynx.tech www.api.getlynx.tech;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.getlynx.tech www.api.getlynx.tech;

    ssl_certificate /etc/letsencrypt/live/getlynx.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/getlynx.tech/privkey.pem;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
}